=== DEIB-GECO/GMQL-Importer/Example/xml/configurationSchema.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://polimi.it/GDMImporter"
           xmlns="http://polimi.it/GDMImporter"
           elementFormDefault="qualified">
    <xs:element name="root" type="root_type">
        <xs:annotation>
            <xs:documentation>Literally the root of the xml document.</xs:documentation>
        </xs:annotation>
    </xs:element>
    <xs:complexType name="settings_type">
        <xs:annotation>
            <xs:documentation>Contains the general settings for the application.</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element type="xs:string" name="base_working_directory">
                <xs:annotation>
                    <xs:documentation>Root working directory for the application.</xs:documentation>
                    <xs:documentation>Paths inside the configuration xml are relative to this path.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element type="xs:string" name="gcm_config_file">
                <xs:annotation>
                    <xs:documentation>GCM configuration file path</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element type="xs:string" name="mapper_source">
                <xs:annotation>
                    <xs:documentation>name of the source parameter to run mapper with correct method (ENCODE,TCGA,ANN,CISTROME,TADS_RAO,TADS_COMB)</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element type="xs:string" name="database_connection_url">
                <xs:annotation>
                    <xs:documentation>database_connection_url</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element type="xs:string" name="database_connection_user">
                <xs:annotation>
                    <xs:documentation>database_connection_user</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element type="xs:string" name="database_connection_pw">
                <xs:annotation>
                    <xs:documentation>database_connection_pw</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element type="xs:string" name="database_connection_driver">
                <xs:annotation>
                    <xs:documentation>database_connection_driver</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element type="xs:string" name="flattener_rule_base">
                <xs:annotation>
                    <xs:documentation>Flattener rule base</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element type="xs:boolean" name="download_enabled">
                <xs:annotation>
                    <xs:documentation>Top level filter for allowing the application to download.</xs:documentation>
                    <xs:documentation>If false, no source will be downloaded.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element type="xs:boolean" name="transform_enabled">
                <xs:annotation>
                    <xs:documentation>Top level filter for allowing the application to transform.</xs:documentation>
                    <xs:documentation>If false, no source will be transformed.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element type="xs:boolean" name="cleaner_enabled">
                <xs:annotation>
                    <xs:documentation></xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element type="xs:boolean" name="mapper_enabled">
                <xs:annotation>
                    <xs:documentation></xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element type="xs:boolean" name="enricher_enabled">
                <xs:annotation>
                    <xs:documentation></xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element type="xs:boolean" name="flattener_enabled">
                <xs:annotation>
                    <xs:documentation></xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element type="xs:boolean" name="load_enabled">
                <xs:annotation>
                    <xs:documentation>Top level filter for allowing the application to load.</xs:documentation>
                    <xs:documentation>If false, no source will be loaded.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element type="xs:boolean" name="parallel_execution">
                <xs:annotation>
                    <xs:documentation>decides whether the application runs with multiple threads or not.</xs:documentation>
                    <xs:documentation>If false, no parallel execution is enabled.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="parameter_type">
        <xs:annotation>
            <xs:documentation>Generic parameter with description, key name and value.</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element type="xs:string" name="description" minOccurs="0">
                <xs:annotation>
                    <xs:documentation>Explanation of what means the parameter in the application.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element type="xs:string" name="type" minOccurs="0">
                <xs:annotation>
                    <xs:documentation>type for parameter, when multiple values to use in a single parameter.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element type="xs:string" name="key">
                <xs:annotation>
                    <xs:documentation>Name of the parameter.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element type="xs:string" name="value">
                <xs:annotation>
                    <xs:documentation>value of the parameter.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="parameter_list_type">
        <xs:annotation>
            <xs:documentation>List of parameters for source/dataset.</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element type="parameter_type" name="parameter" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    <xs:simpleType name="schema_location_type" final="restriction">
        <xs:annotation>
            <xs:documentation>Enumeration of possible locations for the schema files.</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:enumeration value="local">
                <xs:annotation>
                    <xs:documentation>Schema file is inside the root working directory.</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="http">
                <xs:annotation>
                    <xs:documentation>Access through http.</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="schema_type">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="schema_location_type" name="location" use="required">
                    <xs:annotation>
                        <xs:documentation>Url for the schema file of the dataset.</xs:documentation>
                    </xs:annotation>
                </xs:attribute>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="dataset_type">
        <xs:annotation>
            <xs:documentation>Represents a dataset, it belongs to a source and has internal settings.</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element type="xs:string" name="dataset_working_directory">
                <xs:annotation>
                    <xs:documentation>Working directory for the dataset, subfolder of its source's working directory.
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element type="schema_type" name="schema_url">
                <xs:annotation>
                    <xs:documentation>URL of the schema file.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element type="xs:boolean" name="download_enabled">
                <xs:annotation>
                    <xs:documentation>Indicates whether the dataset has to be downloaded.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element type="xs:boolean" name="transform_enabled">
                <xs:annotation>
                    <xs:documentation>Indicates whether the dataset has to be transformed.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element type="xs:boolean" name="cleaner_enabled">
                <xs:annotation>
                    <xs:documentation></xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element type="xs:boolean" name="mapper_enabled">
                <xs:annotation>
                    <xs:documentation></xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element type="xs:boolean" name="enricher_enabled">
                <xs:annotation>
                    <xs:documentation></xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element type="xs:boolean" name="flattener_enabled">
                <xs:annotation>
                    <xs:documentation></xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element type="xs:boolean" name="load_enabled">
                <xs:annotation>
                    <xs:documentation>Indicates whether the dataset has to be loaded.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element type="parameter_list_type" name="parameter_list">
                <xs:annotation>
                    <xs:documentation>List of parameters for the dataset.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
        <xs:attribute type="xs:string" name="name" use="required">
            <xs:annotation>
                <xs:documentation>Name of the dataset, final name will be "sourceName"_"datasetName".</xs:documentation>
            </xs:annotation>
        </xs:attribute>
    </xs:complexType>
    <xs:complexType name="dataset_list_type">
        <xs:annotation>
            <xs:documentation>List of datasets inside a source.</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element type="dataset_type" name="dataset" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="source_type">
        <xs:annotation>
            <xs:documentation>Represents a source, it has internal settings and contains a list of datasets.
            </xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element type="xs:string" name="url">
                <xs:annotation>
                    <xs:documentation>Url address for the source.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element type="xs:string" name="source_working_directory">
                <xs:annotation>
                    <xs:documentation>Working directory of the source, subfolder of root working directory
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element type="xs:string" name="downloader">
                <xs:annotation>
                    <xs:documentation>Indicates which downloader has to be used by the source.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element type="xs:string" name="transformer">
                <xs:annotation>
                    <xs:documentation>Indicates which transformer has to be used by the source.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element type="xs:string" name="loader">
                <xs:annotation>
                    <xs:documentation>Indicates which loader has to be used by the source.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element type="xs:boolean" name="download_enabled">
                <xs:annotation>
                    <xs:documentation>Indicates whether the source is enabled to be downloaded, rules over dataset and
                        is ruled by root settings.
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element type="xs:boolean" name="transform_enabled">
                <xs:annotation>
                    <xs:documentation>Indicates whether the source is enabled to be transformed, rules over dataset and
                        is ruled by root settings.
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element type="xs:boolean" name="cleaner_enabled">
                <xs:annotation>
                    <xs:documentation></xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element type="xs:boolean" name="mapper_enabled">
                <xs:annotation>
                    <xs:documentation></xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element type="xs:boolean" name="enricher_enabled">
                <xs:annotation>
                    <xs:documentation></xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element type="xs:boolean" name="flattener_enabled">
                <xs:annotation>
                    <xs:documentation></xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element type="xs:boolean" name="load_enabled">
                <xs:annotation>
                    <xs:documentation>Indicates whether the source is enabled to be loaded, rules over dataset and is
                        ruled by root settings.
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element type="parameter_list_type" name="parameter_list">
                <xs:annotation>
                    <xs:documentation>List of parameters needed for the source.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element type="dataset_list_type" name="dataset_list">
                <xs:annotation>
                    <xs:documentation>List of datasets contained by the source.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
        <xs:attribute type="xs:string" name="name" use="required">
            <xs:annotation>
                <xs:documentation>Name for which the source is going to be handled.</xs:documentation>
            </xs:annotation>
        </xs:attribute>
    </xs:complexType>
    <xs:complexType name="source_list_type">
        <xs:annotation>
            <xs:documentation>List of sources to be handled in the configuration file.</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element type="source_type" name="source" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="root_type">
        <xs:annotation>
            <xs:documentation>Root node contains general settings and list of sources.</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element type="settings_type" name="settings"/>
            <xs:element type="source_list_type" name="source_list"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== DEIB-GECO/GMQL-Importer/Example/xml/Consistent_Config_XMLs_REMOTE/ConfigurationCistrome.xml
<?xml version="1.0"?>
<root xmlns="http://polimi.it/GDMImporter"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://polimi.it/GDMImporter /Example/xml/configurationSchema.xsd">
    <settings>
        <!--BASE WORKING FOLDER FOR THE IMPORTER-->
        <base_working_directory>/home/hduser/gmql_importer/</base_working_directory>
        <gcm_config_file>/home/hduser/gmql_importer/conf/application.conf</gcm_config_file>
        <flattener_rule_base>/home/hduser/GMQL-sources/Metadata-Manager/Example/flattener_rule_base.txt
        </flattener_rule_base>
        <download_enabled>false</download_enabled>
        <transform_enabled>false</transform_enabled>
        <cleaner_enabled>false</cleaner_enabled>
        <mapper_enabled>false</mapper_enabled>
        <enricher_enabled>false</enricher_enabled>
        <flattener_enabled>true</flattener_enabled>
        <load_enabled>false</load_enabled>
        <parallel_execution>false</parallel_execution>
    </settings>
    <source_list>
        <source name="GRCh38_CISTROME">
            <url>http://cistrome.org/~rongbin/data_release/</url>
            <source_working_directory>cistrome</source_working_directory>
            <downloader>it.polimi.genomics.importer.CistromeImporter.CistromeDownloader</downloader>
            <transformer>it.polimi.genomics.importer.CistromeImporter.CistromeTransformer</transformer>
            <loader>it.polimi.genomics.importer.GMQLImporter.GMQLLoader</loader>
            <download_enabled>true</download_enabled>
            <transform_enabled>true</transform_enabled>
            <cleaner_enabled>true</cleaner_enabled>
            <mapper_enabled>true</mapper_enabled>
            <enricher_enabled>true</enricher_enabled>
            <flattener_enabled>true</flattener_enabled>
            <load_enabled>true</load_enabled>
            <parameter_list>
                <parameter>
                    <description>to know which user in gmql is going to be imported</description>
                    <key>gmql_user</key>
                    <value>leone</value>
                </parameter>
                <parameter>
                    <description>onassis file path</description>
                    <key>onassis_file_path</key>
                    <value>/home/hduser/gmql_importer/conf/onassis.txt</value>
                </parameter>
                <!--<parameter>
                    <description>Cleaner definition rule base file</description>
                    <key>rule_base</key>
                    <value>/home/hduser/gmql_importer/CISTROME_rules.txt</value>
                </parameter>-->
            </parameter_list>
            <dataset_list>
                <dataset name="narrowPeak">
                    <dataset_working_directory>narrowPeak</dataset_working_directory>
                    <schema_url location="local">schemas/narrowPeak.schema</schema_url>
                    <download_enabled>true</download_enabled>
                    <transform_enabled>true</transform_enabled>
                    <cleaner_enabled>true</cleaner_enabled>
                    <mapper_enabled>true</mapper_enabled>
                    <enricher_enabled>true</enricher_enabled>
                    <flattener_enabled>true</flattener_enabled>
                    <load_enabled>true</load_enabled>
                    <parameter_list>
                        <parameter>
                            <key>loading_description</key>
                            <value>This dataset constains ChIP-seq and chromatin accessibility data aligned to human
                                genome assembly GRCh38, collected from the NCBI GEO database, ENCODE database and
                                Roadmap Epigenomics project
                            </value>
                        </parameter>
                        <parameter>
                            <key>file_filter</key>
                            <value>(.*narrowPeak.*)</value>
                        </parameter>
                        <parameter>
                            <key>file_metadata</key>
                            <value>(.*data_information.*)</value>
                        </parameter>
                        <parameter>
                            <key>file_full_path</key>
                            <value>http://cistrome.org/~rongbin/data_release/histone_human.tar.gz</value>
                        </parameter>
                    </parameter_list>
                </dataset>
                <dataset name="broadPeak">
                    <dataset_working_directory>broadPeak</dataset_working_directory>
                    <schema_url location="local">schemas/broadPeak.schema</schema_url>
                    <download_enabled>true</download_enabled>
                    <transform_enabled>false</transform_enabled>
                    <cleaner_enabled>true</cleaner_enabled>
                    <mapper_enabled>true</mapper_enabled>
                    <enricher_enabled>true</enricher_enabled>
                    <flattener_enabled>true</flattener_enabled>
                    <load_enabled>true</load_enabled>
                    <parameter_list>
                        <parameter>
                            <key>loading_description</key>
                            <value>This dataset constains ChIP-seq and chromatin accessibility data aligned to human
                                genome assembly GRCh38, collected from the NCBI GEO database, ENCODE database and
                                Roadmap Epigenomics project
                            </value>
                        </parameter>
                        <parameter>
                            <key>file_filter</key>
                            <value>(.*broadPeak.*)</value>
                        </parameter>
                        <parameter>
                            <key>file_metadata</key>
                            <value>(.*data_information.*)</value>
                        </parameter>
                        <parameter>
                            <key>file_full_path</key>
                            <value>http://cistrome.org/~rongbin/data_release/histone_human.tar.gz</value>
                        </parameter>
                    </parameter_list>
                </dataset>
            </dataset_list>
        </source>
    </source_list>
</root>

=== DEIB-GECO/GMQL-Importer/Example/xml/ConfigurationCistrome.xml
<?xml version="1.0"?>
<root   xmlns="http://polimi.it/GDMImporter"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://polimi.it/GDMImporter /Example/xml/configurationSchema.xsd">
    <settings>
        <!--BASE WORKING FOLDER FOR THE IMPORTER-->
        <base_working_directory>/Users/canakoglu/Downloads/michele/downloader</base_working_directory>
        <download_enabled>false</download_enabled>
        <transform_enabled>true</transform_enabled>
        <load_enabled>false</load_enabled>
        <parallel_execution>false</parallel_execution>
    </settings>
    <source_list>
        <source name="CISTROME">
            <url>http://cistrome.org/~rongbin/data_release/</url>
            <source_working_directory>cistrome</source_working_directory>
            <downloader>it.polimi.genomics.importer.CistromeImporter.CistromeDownloader</downloader>
            <transformer>it.polimi.genomics.importer.CistromeImporter.CistromeTransformer</transformer>
            <loader>it.polimi.genomics.importer.GMQLImporter.GMQLLoader</loader>
            <download_enabled>true</download_enabled>
            <transform_enabled>true</transform_enabled>
            <load_enabled>true</load_enabled>
            <parameter_list>     
                <parameter>
                    <description>to know which user in gmql is going to be imported</description>
                    <key>gmql_user</key>
                    <value>public</value>
                </parameter>
            </parameter_list>
            <dataset_list>
                <dataset name="HG19_TEST_N">
                    <dataset_working_directory>human_tf</dataset_working_directory>
                    <schema_url location="local">schemas/narrowPeak.schema</schema_url>
                    <download_enabled>true</download_enabled>
                    <transform_enabled>true</transform_enabled>
                    <load_enabled>false</load_enabled>
                    <parameter_list>
                        <parameter>
                            <key>loading_description</key>
                            <value>Pippo description</value>
                        </parameter>
                        <parameter>
                            <key>file_filter</key>
                            <value>(.*narrowPeak.*)</value>
                        </parameter>
                        <parameter>
                            <key>file_metadata</key>
                            <value>(.*data_information.*)</value>
                        </parameter>

                        <parameter>
                            <key>file_full_path</key>
                            <value>http://cistrome.org/~rongbin/data_release/histone_human.tar.gz</value>
                        </parameter>

                    </parameter_list>
                </dataset>
            </dataset_list>
        </source>
    </source_list>
</root>
