=== DEIB-GECO/GMQL-Importer/Example/xml/configurationSchema.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://polimi.it/GDMImporter"
           xmlns="http://polimi.it/GDMImporter"
           elementFormDefault="qualified">
    <xs:element name="root" type="root_type">
        <xs:annotation>
            <xs:documentation>Literally the root of the xml document.</xs:documentation>
        </xs:annotation>
    </xs:element>
    <xs:complexType name="settings_type">
        <xs:annotation>
            <xs:documentation>Contains the general settings for the application.</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element type="xs:string" name="base_working_directory">
                <xs:annotation>
                    <xs:documentation>Root working directory for the application.</xs:documentation>
                    <xs:documentation>Paths inside the configuration xml are relative to this path.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element type="xs:string" name="gcm_config_file">
                <xs:annotation>
                    <xs:documentation>GCM configuration file path</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element type="xs:string" name="mapper_source">
                <xs:annotation>
                    <xs:documentation>name of the source parameter to run mapper with correct method (ENCODE,TCGA,ANN,CISTROME,TADS_RAO,TADS_COMB)</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element type="xs:string" name="database_connection_url">
                <xs:annotation>
                    <xs:documentation>database_connection_url</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element type="xs:string" name="database_connection_user">
                <xs:annotation>
                    <xs:documentation>database_connection_user</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element type="xs:string" name="database_connection_pw">
                <xs:annotation>
                    <xs:documentation>database_connection_pw</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element type="xs:string" name="database_connection_driver">
                <xs:annotation>
                    <xs:documentation>database_connection_driver</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element type="xs:string" name="flattener_rule_base">
                <xs:annotation>
                    <xs:documentation>Flattener rule base</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element type="xs:boolean" name="download_enabled">
                <xs:annotation>
                    <xs:documentation>Top level filter for allowing the application to download.</xs:documentation>
                    <xs:documentation>If false, no source will be downloaded.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element type="xs:boolean" name="transform_enabled">
                <xs:annotation>
                    <xs:documentation>Top level filter for allowing the application to transform.</xs:documentation>
                    <xs:documentation>If false, no source will be transformed.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element type="xs:boolean" name="cleaner_enabled">
                <xs:annotation>
                    <xs:documentation></xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element type="xs:boolean" name="mapper_enabled">
                <xs:annotation>
                    <xs:documentation></xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element type="xs:boolean" name="enricher_enabled">
                <xs:annotation>
                    <xs:documentation></xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element type="xs:boolean" name="flattener_enabled">
                <xs:annotation>
                    <xs:documentation></xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element type="xs:boolean" name="load_enabled">
                <xs:annotation>
                    <xs:documentation>Top level filter for allowing the application to load.</xs:documentation>
                    <xs:documentation>If false, no source will be loaded.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element type="xs:boolean" name="parallel_execution">
                <xs:annotation>
                    <xs:documentation>decides whether the application runs with multiple threads or not.</xs:documentation>
                    <xs:documentation>If false, no parallel execution is enabled.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="parameter_type">
        <xs:annotation>
            <xs:documentation>Generic parameter with description, key name and value.</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element type="xs:string" name="description" minOccurs="0">
                <xs:annotation>
                    <xs:documentation>Explanation of what means the parameter in the application.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element type="xs:string" name="type" minOccurs="0">
                <xs:annotation>
                    <xs:documentation>type for parameter, when multiple values to use in a single parameter.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element type="xs:string" name="key">
                <xs:annotation>
                    <xs:documentation>Name of the parameter.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element type="xs:string" name="value">
                <xs:annotation>
                    <xs:documentation>value of the parameter.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="parameter_list_type">
        <xs:annotation>
            <xs:documentation>List of parameters for source/dataset.</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element type="parameter_type" name="parameter" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    <xs:simpleType name="schema_location_type" final="restriction">
        <xs:annotation>
            <xs:documentation>Enumeration of possible locations for the schema files.</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:enumeration value="local">
                <xs:annotation>
                    <xs:documentation>Schema file is inside the root working directory.</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="http">
                <xs:annotation>
                    <xs:documentation>Access through http.</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="schema_type">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="schema_location_type" name="location" use="required">
                    <xs:annotation>
                        <xs:documentation>Url for the schema file of the dataset.</xs:documentation>
                    </xs:annotation>
                </xs:attribute>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="dataset_type">
        <xs:annotation>
            <xs:documentation>Represents a dataset, it belongs to a source and has internal settings.</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element type="xs:string" name="dataset_working_directory">
                <xs:annotation>
                    <xs:documentation>Working directory for the dataset, subfolder of its source's working directory.
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element type="schema_type" name="schema_url">
                <xs:annotation>
                    <xs:documentation>URL of the schema file.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element type="xs:boolean" name="download_enabled">
                <xs:annotation>
                    <xs:documentation>Indicates whether the dataset has to be downloaded.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element type="xs:boolean" name="transform_enabled">
                <xs:annotation>
                    <xs:documentation>Indicates whether the dataset has to be transformed.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element type="xs:boolean" name="cleaner_enabled">
                <xs:annotation>
                    <xs:documentation></xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element type="xs:boolean" name="mapper_enabled">
                <xs:annotation>
                    <xs:documentation></xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element type="xs:boolean" name="enricher_enabled">
                <xs:annotation>
                    <xs:documentation></xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element type="xs:boolean" name="flattener_enabled">
                <xs:annotation>
                    <xs:documentation></xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element type="xs:boolean" name="load_enabled">
                <xs:annotation>
                    <xs:documentation>Indicates whether the dataset has to be loaded.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element type="parameter_list_type" name="parameter_list">
                <xs:annotation>
                    <xs:documentation>List of parameters for the dataset.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
        <xs:attribute type="xs:string" name="name" use="required">
            <xs:annotation>
                <xs:documentation>Name of the dataset, final name will be "sourceName"_"datasetName".</xs:documentation>
            </xs:annotation>
        </xs:attribute>
    </xs:complexType>
    <xs:complexType name="dataset_list_type">
        <xs:annotation>
            <xs:documentation>List of datasets inside a source.</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element type="dataset_type" name="dataset" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="source_type">
        <xs:annotation>
            <xs:documentation>Represents a source, it has internal settings and contains a list of datasets.
            </xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element type="xs:string" name="url">
                <xs:annotation>
                    <xs:documentation>Url address for the source.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element type="xs:string" name="source_working_directory">
                <xs:annotation>
                    <xs:documentation>Working directory of the source, subfolder of root working directory
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element type="xs:string" name="downloader">
                <xs:annotation>
                    <xs:documentation>Indicates which downloader has to be used by the source.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element type="xs:string" name="transformer">
                <xs:annotation>
                    <xs:documentation>Indicates which transformer has to be used by the source.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element type="xs:string" name="loader">
                <xs:annotation>
                    <xs:documentation>Indicates which loader has to be used by the source.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element type="xs:boolean" name="download_enabled">
                <xs:annotation>
                    <xs:documentation>Indicates whether the source is enabled to be downloaded, rules over dataset and
                        is ruled by root settings.
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element type="xs:boolean" name="transform_enabled">
                <xs:annotation>
                    <xs:documentation>Indicates whether the source is enabled to be transformed, rules over dataset and
                        is ruled by root settings.
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element type="xs:boolean" name="cleaner_enabled">
                <xs:annotation>
                    <xs:documentation></xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element type="xs:boolean" name="mapper_enabled">
                <xs:annotation>
                    <xs:documentation></xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element type="xs:boolean" name="enricher_enabled">
                <xs:annotation>
                    <xs:documentation></xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element type="xs:boolean" name="flattener_enabled">
                <xs:annotation>
                    <xs:documentation></xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element type="xs:boolean" name="load_enabled">
                <xs:annotation>
                    <xs:documentation>Indicates whether the source is enabled to be loaded, rules over dataset and is
                        ruled by root settings.
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element type="parameter_list_type" name="parameter_list">
                <xs:annotation>
                    <xs:documentation>List of parameters needed for the source.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element type="dataset_list_type" name="dataset_list">
                <xs:annotation>
                    <xs:documentation>List of datasets contained by the source.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
        <xs:attribute type="xs:string" name="name" use="required">
            <xs:annotation>
                <xs:documentation>Name for which the source is going to be handled.</xs:documentation>
            </xs:annotation>
        </xs:attribute>
    </xs:complexType>
    <xs:complexType name="source_list_type">
        <xs:annotation>
            <xs:documentation>List of sources to be handled in the configuration file.</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element type="source_type" name="source" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="root_type">
        <xs:annotation>
            <xs:documentation>Root node contains general settings and list of sources.</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element type="settings_type" name="settings"/>
            <xs:element type="source_list_type" name="source_list"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== DEIB-GECO/GMQL-Importer/Example/xml/Consistent_Config_XMLs_LOCAL/ConfigurationOPENGDC_2019_10.xml
<?xml version="1.0"?>
<root   xmlns="http://polimi.it/GDMImporter"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://polimi.it/GDMImporter /Example/xml/configurationSchema.xsd">
    <settings>
        <!--BASE WORKING FOLDER FOR THE IMPORTER-->
        <base_working_directory>/Users/abernasconi/Documents/gitProjects/GMQL-Importer/Example/examples_meta</base_working_directory>
        <!--<gcm_config_file>/Users/abernasconi/Documents/gitProjects/GMQL-Importer/src/main/resources/application.conf</gcm_config_file>
        <mapper_source>TCGA</mapper_source>
        <database_connection_url>jdbc:postgresql://localhost/gmql_metadata_anna</database_connection_url>
        <database_connection_user>geco</database_connection_user>
        <database_connection_pw>geco78</database_connection_pw>
        <database_connection_driver>org.postgresql.Driver</database_connection_driver>
        <flattener_rule_base>/Users/abernasconi/Documents/gitProjects/GMQL-Importer/Example/flattener_rule_base.txt</flattener_rule_base>-->
        <download_enabled>true</download_enabled>
        <transform_enabled>false</transform_enabled>
        <cleaner_enabled>false</cleaner_enabled>
        <mapper_enabled>false</mapper_enabled>
        <enricher_enabled>false</enricher_enabled>
        <flattener_enabled>false</flattener_enabled>
        <load_enabled>false</load_enabled>
        <parallel_execution>false</parallel_execution>
    </settings>
    <source_list>
        <source name="GRCh38_TCGA_OPENGDC_V2">
            <!--url is the host in the FTPDownloader-->
            <url>geco.deib.polimi.it</url>
            <source_working_directory>GRCh38_TCGA_OPENGDC_V2</source_working_directory>
            <downloader>it.polimi.genomics.metadata.downloader_transformer.default.FtpDownloader</downloader>
            <transformer>it.polimi.genomics.metadata.downloader_transformer.default.NullTransformer</transformer>
            <loader>it.polimi.genomics.metadata.step.GMQLLoader</loader>
            <download_enabled>true</download_enabled>
            <transform_enabled>true</transform_enabled>
            <cleaner_enabled>true</cleaner_enabled>
            <mapper_enabled>true</mapper_enabled>
            <enricher_enabled>true</enricher_enabled>
            <flattener_enabled>true</flattener_enabled>
            <load_enabled>true</load_enabled>
            <parameter_list>
                <parameter>
                    <description>For metadata key replacement have to refer another file. Should be big file and would not be useful</description>
                    <key>metadata_replacement</key>
                    <value>xml/metadataReplacementTcga.xml</value>
                </parameter>
                <parameter>
                    <description>It is to know which user in GMQL is going to run the import</description>
                    <key>gmql_user</key>
                    <value>public</value>
                </parameter>
                <parameter>
                    <description>For logging in ftp on tcga2bed we need this anonymous user</description>
                    <key>username</key>
                    <value>anonymous</value>
                </parameter>
                <parameter>
                    <description>And also the corresponding null password</description>
                    <key>password</key>
                    <value/>
                </parameter>
                <parameter>
                    <description>decides the separator char for metadata names.</description>
                    <key>metadata_name_separation_char</key>
                    <value>__</value>
                </parameter>
                <!--<parameter>
                    <description>Mappings</description>
                    <key>mappings</key>
                    <value>/Users/abernasconi/Documents/gitProjects/GMQL-Importer/Example/xml/settingsTCGAOpenGDC.xml</value>
                </parameter>-->
            </parameter_list>
            <dataset_list>
                <!--THE SCHEMA URL HAS TO BE REFERRED FROM ROOT PATH EX: ROOT PATH/SCHEMA PATH/schema.xml-->
                <dataset name="copy_number_segment">
                    <dataset_working_directory>copy_number_segment</dataset_working_directory>
                    <schema_url location="http">ftp://geco.deib.polimi.it/opengdc/bed/tcga/tcga-acc/copy_number_segment/header.schema</schema_url>
                    <download_enabled>true</download_enabled>
                    <transform_enabled>true</transform_enabled>
                    <cleaner_enabled>true</cleaner_enabled>
                    <mapper_enabled>true</mapper_enabled>
                    <enricher_enabled>true</enricher_enabled>
                    <flattener_enabled>true</flattener_enabled>
                    <load_enabled>true</load_enabled>
                    <parameter_list>
                    	<parameter>
                            <description>The dataset name on the server</description>
                            <key>loading_name</key>
                            <value>GRCh38_TCGA_copy_number_2019_10</value>
                        </parameter>
                        <parameter>
                            <description>The dataset description on the server, when clicking Show Info</description>
                            <key>loading_description</key>
                            <value>This dataset contains samples of copy number variations (copy number segment).&lt;br&gt;
                                    A copy number variation (CNV) is a variation in the number of copies of a given genomic segment per cell.&lt;br&gt;
                                    The considered experiments include both germline and somatic CNVs.&lt;br&gt;
                                    &lt;br&gt;
                                    It is directly derived from data available on the Genomic Data Commons portal and transformed into GDM format through the openGDC pipeline.&lt;br&gt;
                                    Documentation is available at http://bioinf.iasi.cnr.it/opengdc/data/OpenGDC_format_definition.pdf.&lt;br&gt;
                                    More details are described in the GDC Data User's Guide available at https://docs.gdc.cancer.gov/Data/PDF/Data_UG.pdf and at https://docs.gdc.cancer.gov/Data/Bioinformatics_Pipelines/CNV_Pipeline/.&lt;br&gt;
                                    &lt;br&gt;
                                    The dataset includes tab separated BED files, in which the CNV file is converted, with the following fields:&lt;br&gt;
                                    &lt;ol&gt;
                                    &lt;li&gt;chrom (equal to the 2. field of the GDC CNV file, e.g., "1")&lt;/li&gt;
                                    &lt;li&gt;start (equal to the 3. field of the GDC CNV file, e.g., 61735)&lt;/li&gt;
                                    &lt;li&gt;end (equal to the 4. field of the GDC CNV file, e.g., 1628826)&lt;/li&gt;
                                    &lt;li&gt;strand (unknown, set to '*')&lt;/li&gt;
                                    &lt;li&gt;num_probes (equal to the 5. field of the GDC CNV file, e.g., 229)&lt;/li&gt;
                                    &lt;li&gt;segment_mean (equal to the 6. field of the GDC CNV file, e.g., 0.1756)&lt;/li&gt;
                                    &lt;/ol&gt;</value>
                        </parameter>
                        <parameter>
                            <description>We look for all the copy_number_segment folders inside the bed directory</description>
                            <key>folder_regex</key>
                            <value>^/opengdc/bed/tcga/tcga-chol/copy_number_segment</value>
                        </parameter>
                        <parameter>
                            <description>We look for all the .bed and .meta files to download</description>
                            <key>files_regex</key>
                            <value>.*\.bed(\.meta)?$</value>
                    </parameter>
                    </parameter_list>
                </dataset>
            </dataset_list>
        </source>
    </source_list>
</root>
